version: '1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:27017"
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1
  nest:
    image: ghcr.io/glumsik/purpleschool_nest/purpleschool_nest:develop
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongo
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mongo

